/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProductionOrder } from "./ProductionOrder";
import { ProductionOrderCountArgs } from "./ProductionOrderCountArgs";
import { ProductionOrderFindManyArgs } from "./ProductionOrderFindManyArgs";
import { ProductionOrderFindUniqueArgs } from "./ProductionOrderFindUniqueArgs";
import { CreateProductionOrderArgs } from "./CreateProductionOrderArgs";
import { UpdateProductionOrderArgs } from "./UpdateProductionOrderArgs";
import { DeleteProductionOrderArgs } from "./DeleteProductionOrderArgs";
import { ProductionQueueFindManyArgs } from "../../productionQueue/base/ProductionQueueFindManyArgs";
import { ProductionQueue } from "../../productionQueue/base/ProductionQueue";
import { Product } from "../../product/base/Product";
import { ProductionOrderService } from "../productionOrder.service";
@graphql.Resolver(() => ProductionOrder)
export class ProductionOrderResolverBase {
  constructor(protected readonly service: ProductionOrderService) {}

  async _productionOrdersMeta(
    @graphql.Args() args: ProductionOrderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProductionOrder])
  async productionOrders(
    @graphql.Args() args: ProductionOrderFindManyArgs
  ): Promise<ProductionOrder[]> {
    return this.service.productionOrders(args);
  }

  @graphql.Query(() => ProductionOrder, { nullable: true })
  async productionOrder(
    @graphql.Args() args: ProductionOrderFindUniqueArgs
  ): Promise<ProductionOrder | null> {
    const result = await this.service.productionOrder(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductionOrder)
  async createProductionOrder(
    @graphql.Args() args: CreateProductionOrderArgs
  ): Promise<ProductionOrder> {
    return await this.service.createProductionOrder({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ProductionOrder)
  async updateProductionOrder(
    @graphql.Args() args: UpdateProductionOrderArgs
  ): Promise<ProductionOrder | null> {
    try {
      return await this.service.updateProductionOrder({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProductionOrder)
  async deleteProductionOrder(
    @graphql.Args() args: DeleteProductionOrderArgs
  ): Promise<ProductionOrder | null> {
    try {
      return await this.service.deleteProductionOrder(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ProductionQueue], { name: "productionQueues" })
  async findProductionQueues(
    @graphql.Parent() parent: ProductionOrder,
    @graphql.Args() args: ProductionQueueFindManyArgs
  ): Promise<ProductionQueue[]> {
    const results = await this.service.findProductionQueues(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(
    @graphql.Parent() parent: ProductionOrder
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
